version: '3.7'
services:
  base:
    image: api-test:${BASE_NAME}
    build:
      context: ..
      dockerfile: ./infra/docker/Dockerfile.base
  app:
    image: api-test:${APP_VERSION}
    build:
      context: ..
      dockerfile: ./infra/docker/Dockerfile
      args:
        - BASE_IMAGE=api-test:${BASE_NAME}
        - APP_NAME=${APP_NAME}
        - APP_VERSION=${APP_VERSION}
        - COMMIT_HASH=${GIT_COMMIT}
    ports:
      - "0.0.0.0:8008:8008"
